
#
# Workflow that utilizes the Dockerfile with a multi stage build to compose the container
# for running the application whilst trying to keep it as small as possible.
#
# Workflow will only execute when the software can successfully build from the sources.
#
name: Container Build

on:
  # Trigger off of the completion of the "Build and Test" workflow execution
  workflow_run:
    workflows:
      - Build and Test
    branches:
      - main
    types:
      - completed

jobs:
  build:
    name: Build Container

    # Only build the container if the source code passed the build and test workflow successfully
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: GitHub Container Registry Login
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker meta
        id: docker_meta
        uses: docker/metadata-action@v3
        with:
          images: ghcr.io/${{ github.repository }}

      - name: Docker Build and Push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ steps.docker_meta.outputs.tags }}
          labels: ${{ steps.docker_meta.outputs.labels }}
