#
# A more complex end to end single workflow that will build and test our code, build a
# container and publish it to the GHCR and then finally deploy it to a cloud based
# environment.
#

name: Continous Delivery

on:
  # push:
  #   - main
  workflow_dispatch:

jobs:
  build:
    name: Build

    strategy:
      matrix:
        os:
          - ubuntu-20.04
        node_version:
          - 16
          - 14

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node_version }}
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Lint
        run: npm run lint

      - name: Build
        run: npm run build

      - name: Save Applicaton Bundle
        uses: actions/upload-artifact@v2
        with:
          name: app-${{ matrix.os }}-${{ matrix.node_version }}
          path: |
            .next
            public
            package.json
            package-lock.json


  #
  # Build the container using the previously built artifacts from the build job
  #
  build_container:
    name: Build Container

    needs:
      - build

    runs-on: ubuntu-20.04

    outputs:
      deployment_container_url: ${{ steps.container_meta.outputs.container_tag }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Unpack Artifact
        uses: actions/download-artifact@v2
        with:
          name: app-ubuntu-20.04-16
          path: continuous-delivery/app

      - name: Restore the node_modules
        run: |
          npm ci
        working-directory: continous-delivery

      # Define the container URL tag for publishing
      - name: Define container tag
        id: container_meta
        run: |
          echo "::set-output name=container_tag::ghcr.io/${{ github.repository }}/${{ github.sha }}"

      - name: Build Container
        run: |
          docker build . --tag ${{ steps.container_meta.outputs.container_tag }}
        working-directory: continuous-delivery

      - name: GitHub Container Registry Login
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push Container to GHCR
        run: |
          docker push ${{ steps.container_meta.outputs.container_tag }}


  #
  # Deploys the container to a Cloud Environment
  #
  deploy:
    name: Deploy to Environment

    needs:
        - build
        - build_container

    runs-on: ubuntu-20.04

    steps:
      - name: Deploy
        run: echo "deploying..."